version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/
    container_name: frontend
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend/public/:/usr/share/nginx/html  # Bind mount pour synchro en dev
    networks:
      - camagru_network

  backend:
    build:
      context: ./backend/
    container_name: backend
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend/public/:/var/www/html/
      - ./backend/static/:/var/www/html/static/
    networks:
      - camagru_network

  db:
    build:
      context: ./db
      args:
        - DB_NAME
        - DB_USER
        - DB_PASSWORD
        - DB_ROOT_PASSWORD
    container_name: db
    restart: always
    env_file:
      - .env
    networks:
      - camagru_network

  proxy:
    build:
      context: ./proxy/
    container_name: proxy
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    networks:
      - camagru_network

volumes:
  backend:
  static:

networks:
  camagru_network: