version: '3.8'
services:
  frontend:
    build:
      context: ./frontend/
      args:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_ROOT_PASSWORD
    container_name: frontend
    restart: always
    env_file:
      - .env
    volumes:
      - frontend:/usr/share/nginx/html:rw
    networks:
      - camagru_network
  backend:
    build:
      context: ./backend/
    container_name: backend
    restart: always
    env_file:
      - .env
    volumes:
      - backend:/var/www/html/:rw
    networks:
      - camagru_network
  db:
    build:
      context: ./db
      args:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    container_name: db
    restart: always
    env_file:
      - .env
    networks:
      - camagru_network
  proxy:
    build:
      context: ./proxy/
    container_name: proxy
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - camagru_network
volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      device: ./frontend/public/
      o: bind
  backend:
    driver: local
    driver_opts:
      type: none
      device: ./backend/public/
      o: bind
networks:
  camagru_network: